const seed={
  vehicles:[
    {id:1,year:2021,make:'Nissan',model:'Altima',plate:'CLC101',mileage:68420,rate:65,status:'Rented',revenue:6240,gps:'https://maps.google.com'},
    {id:2,year:2020,make:'Toyota',model:'Camry',plate:'CLC202',mileage:75310,rate:70,status:'Available',revenue:7150,gps:''},
    {id:3,year:2019,make:'Chevrolet',model:'Malibu',plate:'CLC303',mileage:89215,rate:60,status:'Service',revenue:4980,gps:''},
    {id:4,year:2022,make:'Kia',model:'Forte',plate:'CLC404',mileage:52100,rate:68,status:'Rented',revenue:6820,gps:'https://maps.google.com'}],
  customers:[
    {id:1,name:'Jordan Mills',phone:'229-555-0148',email:'jordan@example.com',license:'GA •••• 9214',docs:{}},
    {id:2,name:'Ashley Brown',phone:'229-555-0177',email:'ashley@example.com',license:'GA •••• 4450',docs:{}},
    {id:3,name:'Marcus Green',phone:'229-555-0194',email:'marcus@example.com',license:'GA •••• 1832',docs:{}}],
  rentals:[
    {id:1,customer:'Jordan Mills',vehicle:'2021 Nissan Altima',pickup:'2026-08-04',return:'2026-08-07',balance:0,status:'Active',lateFeeDaily:35},
    {id:2,customer:'Ashley Brown',vehicle:'2022 Kia Forte',pickup:'2026-08-01',return:'2026-08-05',balance:136,status:'Overdue',lateFeeDaily:35},
    {id:3,customer:'Marcus Green',vehicle:'2020 Toyota Camry',pickup:'2026-08-09',return:'2026-08-12',balance:210,status:'Upcoming',lateFeeDaily:35}],
  payments:[{date:'2026-08-04',customer:'Jordan Mills',type:'Rental',method:'Card',amount:195,status:'Paid'},{date:'2026-08-01',customer:'Ashley Brown',type:'Deposit',method:'Cash App',amount:200,status:'Paid'},{date:'2026-08-05',customer:'Ashley Brown',type:'Extension',method:'Pending',amount:136,status:'Pending'}],
  maintenance:[{vehicle:'2019 Chevrolet Malibu',service:'Brake inspection',due:'Due now',status:'Due'},{vehicle:'2021 Nissan Altima',service:'Oil change',due:'1,580 miles',status:'Upcoming'},{vehicle:'2020 Toyota Camry',service:'Tire rotation',due:'3,200 miles',status:'Upcoming'}],
  agreements:[], inspections:[],
  settings:{defaultLateFee:35,paymentLink:'',reminderHours:24}
};
let data=JSON.parse(localStorage.getItem('clcDataV2'))||JSON.parse(localStorage.getItem('clcData'))||structuredClone(seed);
if(!data.agreements)data.agreements=[]; if(!data.inspections)data.inspections=[]; if(!data.settings)data.settings=structuredClone(seed.settings); data.customers.forEach(c=>c.docs=c.docs||{}); data.vehicles.forEach(v=>v.gps=v.gps||''); data.rentals.forEach(r=>r.lateFeeDaily=Number(r.lateFeeDaily||data.settings.defaultLateFee||35));
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('clcDataV2',JSON.stringify(data));renderAll()}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#email').value==='admin@citylifecars.com'&&$('#password').value==='CityLife2026'){sessionStorage.setItem('clcAuth','1');showApp()}else $('#loginError').textContent='Incorrect email or password.'});
function showApp(){$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');renderAll()}
if(sessionStorage.getItem('clcAuth'))showApp(); $('#logoutBtn').onclick=()=>{sessionStorage.removeItem('clcAuth');location.reload()};
$$('.nav-link').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.jump));
function switchView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#pageTitle').textContent=id==='settings'?'Settings & Backup':id[0].toUpperCase()+id.slice(1);$('#sidebar').classList.remove('open')}
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open'); const badge=s=>`<span class="badge ${String(s).toLowerCase()}">${s}</span>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function daysLate(r){if(r.status==='Completed')return 0;const now=new Date();now.setHours(0,0,0,0);const due=new Date(r.return+'T00:00:00');return Math.max(0,Math.floor((now-due)/86400000))}
function lateFee(r){return daysLate(r)*Number(r.lateFeeDaily||data.settings.defaultLateFee||0)}
function autoRentalStatus(r){const late=daysLate(r);if(r.status!=='Completed'&&late>0)r.status='Overdue';return r.status}
function renderAll(){data.rentals.forEach(autoRentalStatus); const active=data.rentals.filter(r=>['Active','Overdue'].includes(r.status)).length,available=data.vehicles.filter(v=>v.status==='Available').length,overdue=data.rentals.filter(r=>r.status==='Overdue').length,revenue=data.payments.filter(p=>p.status==='Paid').reduce((a,p)=>a+Number(p.amount),0);
  $('#statsGrid').innerHTML=[[available,'Vehicles Available','Ready to rent'],[active,'Active Rentals','Currently on the road'],[overdue,'Overdue Returns','Needs attention'],['$'+revenue.toLocaleString(),'Revenue Recorded','Current records']].map(x=>`<div class="stat-card"><small>${x[1]}</small><strong>${x[0]}</strong><div class="trend">${x[2]}</div></div>`).join('');
  $('#dueList').innerHTML=data.rentals.filter(r=>r.status!=='Completed').map(r=>`<div class="due-row"><div><strong>${esc(r.customer)}</strong><div class="muted">${esc(r.vehicle)} • Return ${r.return}${daysLate(r)?` • ${daysLate(r)} day(s) late`:''}</div></div>${badge(r.status)}</div>`).join('')||'<p class="muted">No open rentals.</p>';
  $('#fleetStatus').innerHTML=['Available','Rented','Service'].map(s=>`<div class="status-row"><span>${s}</span><strong>${data.vehicles.filter(v=>v.status===s).length}</strong></div>`).join('');
  $('#fleetTable').innerHTML=data.vehicles.map(v=>`<tr><td><strong>${v.year} ${esc(v.make)} ${esc(v.model)}</strong></td><td>${esc(v.plate)}</td><td>${Number(v.mileage).toLocaleString()}</td><td>$${v.rate}</td><td>${v.gps?`<a href="${esc(v.gps)}" target="_blank" rel="noopener">Open GPS</a>`:'—'}</td><td>${badge(v.status)}</td></tr>`).join('');
  $('#rentalsTable').innerHTML=data.rentals.map(r=>`<tr class="${r.status==='Overdue'?'overdue-row':''}"><td><strong>${esc(r.customer)}</strong></td><td>${esc(r.vehicle)}</td><td>${r.pickup}</td><td>${r.return}</td><td>$${lateFee(r).toFixed(2)}</td><td>$${(Number(r.balance)+lateFee(r)).toFixed(2)}</td><td>${badge(r.status)}</td></tr>`).join('');
  $('#customerCards').innerHTML=data.customers.map(c=>`<article class="customer-card"><h3>${esc(c.name)}</h3><p>${esc(c.phone)}</p><p>${esc(c.email)}</p><p>${esc(c.license)}</p><div class="doc-status"><span class="mini-pill">License: ${c.docs.license?'✓':'Missing'}</span><span class="mini-pill">Insurance: ${c.docs.insurance?'✓':'Missing'}</span></div><button class="outline-btn" onclick="openDocModal(${c.id})">Documents</button></article>`).join('');
  const paid=data.payments.filter(p=>p.status==='Paid').reduce((a,p)=>a+Number(p.amount),0),pending=data.payments.filter(p=>p.status==='Pending').reduce((a,p)=>a+Number(p.amount),0);$('#paymentStats').innerHTML=[[`$${paid.toFixed(2)}`,'Payments Collected'],[`$${pending.toFixed(2)}`,'Pending Payments'],[data.payments.length,'Transactions'],['Hosted','Card Processing']].map(x=>`<div class="stat-card"><small>${x[1]}</small><strong>${x[0]}</strong></div>`).join('');
  $('#paymentsTable').innerHTML=data.payments.map(p=>`<tr><td>${p.date}</td><td>${esc(p.customer)}</td><td>${esc(p.type)}</td><td>${esc(p.method)}</td><td>$${Number(p.amount).toFixed(2)}</td><td>${badge(p.status)}</td></tr>`).join('');
  $('#maintenanceList').innerHTML=data.maintenance.map(m=>`<article class="maintenance-card"><h3>${esc(m.vehicle)}</h3><p>${esc(m.service)}</p><p><strong>${esc(m.due)}</strong></p>${badge(m.status==='Due'?'Due':'Service')}</article>`).join('');
  const totalRev=data.vehicles.reduce((a,v)=>a+Number(v.revenue||0),0);$('#reportStats').innerHTML=[[`$${totalRev.toLocaleString()}`,'Lifetime Vehicle Revenue'],[`${data.vehicles.length?Math.round(active/data.vehicles.length*100):0}%`,'Fleet Utilization'],[`$${data.rentals.reduce((a,r)=>a+Number(r.balance)+lateFee(r),0).toFixed(2)}`,'Outstanding + Late Fees'],['$'+Math.round(totalRev/Math.max(1,data.vehicles.length)).toLocaleString(),'Average per Vehicle']].map(x=>`<div class="stat-card"><small>${x[1]}</small><strong>${x[0]}</strong></div>`).join('');
  const max=Math.max(1,...data.vehicles.map(v=>Number(v.revenue||0)));$('#revenueBars').innerHTML=data.vehicles.map(v=>`<div class="bar-row"><span>${esc(v.make)} ${esc(v.model)}</span><div class="bar-track"><div class="bar-fill" style="width:${Number(v.revenue||0)/max*100}%"></div></div><strong>$${Number(v.revenue||0)}</strong></div>`).join('');
  renderAgreements();renderInspections();renderReminders();renderSettings();
}
const forms={
 vehicle:{title:'Add Vehicle',fields:[['year','Year','number'],['make','Make','text'],['model','Model','text'],['plate','License Plate','text'],['mileage','Mileage','number'],['rate','Daily Rate','number'],['gps','GPS Tracking Link','url',null,false],['status','Status','select',['Available','Rented','Service']]]},
 customer:{title:'Add Customer',fields:[['name','Full Name','text'],['phone','Phone','tel'],['email','Email','email'],['license','License Number','text']]},
 payment:{title:'Record Payment',fields:[['date','Date','date'],['customer','Customer','text'],['type','Payment Type','text'],['method','Method','select',['Card - Hosted Checkout','Cash','Cash App','Zelle','Apple Pay']],['amount','Amount','number'],['status','Status','select',['Paid','Pending']]]},
 service:{title:'Add Maintenance',fields:[['vehicle','Vehicle','text'],['service','Service Needed','text'],['due','Due Date or Mileage','text'],['status','Status','select',['Due','Upcoming']]]},
 rental:{title:'Create Rental',fields:[['customer','Customer','text'],['vehicle','Vehicle','text'],['pickup','Pickup Date','date'],['return','Return Date','date'],['balance','Base Balance Due','number'],['lateFeeDaily','Late Fee / Day','number'],['status','Status','select',['Active','Upcoming','Overdue','Completed']]]}
};
window.openModal=type=>{const cfg=forms[type];$('#modalTitle').textContent=cfg.title;$('#recordForm').dataset.type=type;$('#recordForm').innerHTML=cfg.fields.map(f=>f[2]==='select'?`<label>${f[1]}<select name="${f[0]}" required>${f[3].map(o=>`<option>${o}</option>`).join('')}</select></label>`:`<label>${f[1]}<input name="${f[0]}" type="${f[2]}" ${f[4]===false?'':'required'} ${f[0]==='lateFeeDaily'?`value="${data.settings.defaultLateFee}"`:''}></label>`).join('')+`<button class="primary-btn" type="submit">Save Record</button>`;$('#modal').classList.remove('hidden')};
$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#recordForm').onsubmit=e=>{e.preventDefault();const type=e.currentTarget.dataset.type,obj=Object.fromEntries(new FormData(e.currentTarget));['year','mileage','rate','amount','balance','lateFeeDaily'].forEach(k=>{if(obj[k]!==undefined)obj[k]=Number(obj[k])});if(type==='vehicle'){obj.id=Date.now();obj.revenue=0;data.vehicles.push(obj)}else if(type==='customer'){obj.id=Date.now();obj.docs={};data.customers.push(obj)}else if(type==='rental'){obj.id=Date.now();data.rentals.push(obj)}else if(type==='payment')data.payments.push(obj);else data.maintenance.push(obj);save();$('#modal').classList.add('hidden')};

function renderAgreements(){$('#agreementCards').innerHTML=data.agreements.length?data.agreements.map(a=>`<article class="customer-card"><h3>${esc(a.customer)}</h3><p>${esc(a.vehicle)}</p><p>Signed ${a.date}</p><p>Initials: ${esc(a.initials)}</p><div class="agreement-actions"><button class="outline-btn" onclick="printAgreement(${a.id})">Print / PDF</button></div></article>`).join(''):'<p class="muted">No signed agreements yet.</p>'}
window.openAgreementModal=()=>{const options=data.rentals.map(r=>`<option value="${r.id}">${esc(r.customer)} — ${esc(r.vehicle)} (${r.pickup} to ${r.return})</option>`).join('');if(!options){alert('Create a rental first.');return}$('#agreementRental').innerHTML=options;$('#agreementTerms').value=`CITY LIFE CARS RENTAL AGREEMENT\n\nThe renter agrees to return the vehicle by the scheduled return date and time, in substantially the same condition, subject to normal wear. The renter is responsible for authorized charges, fuel, tolls, parking/traffic violations, damage not covered by applicable insurance, and late fees described in the rental record. No unauthorized driver may operate the vehicle. The renter agrees to notify City Life Cars promptly of accidents, theft, mechanical problems, or any change affecting the rental.\n\nThis electronic signature confirms the renter reviewed and accepted these terms.`;$('#agreementDate').value=new Date().toISOString().slice(0,10);$('#agreementModal').classList.remove('hidden');clearCanvas()};
window.closeAgreementModal=()=>$('#agreementModal').classList.add('hidden');
let canvas=$('#signaturePad'),ctx=canvas.getContext('2d'),drawing=false;function canvasPos(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*(canvas.width/r.width),y:(p.clientY-r.top)*(canvas.height/r.height)}}function startDraw(e){drawing=true;const p=canvasPos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function moveDraw(e){if(!drawing)return;const p=canvasPos(e);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#111827';ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function endDraw(){drawing=false}['mousedown','touchstart'].forEach(x=>canvas.addEventListener(x,startDraw,{passive:false}));['mousemove','touchmove'].forEach(x=>canvas.addEventListener(x,moveDraw,{passive:false}));['mouseup','mouseleave','touchend'].forEach(x=>canvas.addEventListener(x,endDraw));function clearCanvas(){ctx.clearRect(0,0,canvas.width,canvas.height)}$('#clearSignature').onclick=clearCanvas;
$('#agreementForm').onsubmit=e=>{e.preventDefault();const r=data.rentals.find(x=>x.id==Number($('#agreementRental').value));data.agreements.push({id:Date.now(),rentalId:r.id,customer:r.customer,vehicle:r.vehicle,pickup:r.pickup,return:r.return,terms:$('#agreementTerms').value,initials:$('#agreementInitials').value,date:$('#agreementDate').value,signature:canvas.toDataURL('image/png')});save();closeAgreementModal()};
window.printAgreement=id=>{const a=data.agreements.find(x=>x.id===id);const w=window.open('','_blank');w.document.write(`<html><head><title>Rental Agreement</title><style>body{font-family:Arial;max-width:800px;margin:40px auto;line-height:1.5}h1{color:#0b1f3a}.box{border:1px solid #ccc;padding:15px;margin:15px 0}img{max-width:420px;border-bottom:1px solid #333}</style></head><body><h1>City Life Cars</h1><h2>Rental Agreement</h2><div class="box"><b>Renter:</b> ${esc(a.customer)}<br><b>Vehicle:</b> ${esc(a.vehicle)}<br><b>Rental dates:</b> ${a.pickup} through ${a.return}<br><b>Date signed:</b> ${a.date}</div><p style="white-space:pre-wrap">${esc(a.terms)}</p><p><b>Renter initials:</b> ${esc(a.initials)}</p><p><b>Electronic signature:</b></p><img src="${a.signature}"><script>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()};

window.openDocModal=id=>{$('#docCustomerId').value=id;$('#docModal').classList.remove('hidden')};window.closeDocModal=()=>$('#docModal').classList.add('hidden');
async function smallFileData(file){if(!file)return null;if(file.size>2_500_000)throw new Error('For this local demo, keep each file under 2.5 MB.');return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res({name:file.name,type:file.type,data:fr.result});fr.onerror=rej;fr.readAsDataURL(file)})}
$('#docForm').onsubmit=async e=>{e.preventDefault();try{const c=data.customers.find(x=>x.id==Number($('#docCustomerId').value));const lf=$('#licenseFile').files[0],inf=$('#insuranceFile').files[0];if(lf)c.docs.license=await smallFileData(lf);if(inf)c.docs.insurance=await smallFileData(inf);save();e.target.reset();closeDocModal()}catch(err){alert(err.message)}};

window.openInspectionModal=()=>{if(!data.rentals.length){alert('Create a rental first.');return}$('#inspectionRental').innerHTML=data.rentals.map(r=>`<option value="${r.id}">${esc(r.customer)} — ${esc(r.vehicle)}</option>`).join('');$('#inspectionModal').classList.remove('hidden')};window.closeInspectionModal=()=>$('#inspectionModal').classList.add('hidden');
async function compressImage(file){return await new Promise((res,rej)=>{const img=new Image(),fr=new FileReader();fr.onload=()=>img.src=fr.result;fr.onerror=rej;img.onload=()=>{const max=900,scale=Math.min(1,max/img.width),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.68))};fr.readAsDataURL(file)})}
$('#inspectionForm').onsubmit=async e=>{e.preventDefault();const r=data.rentals.find(x=>x.id==Number($('#inspectionRental').value));const files=[...$('#inspectionPhotos').files].slice(0,6),photos=[];for(const f of files){if(f.type.startsWith('image/'))photos.push(await compressImage(f))}data.inspections.push({id:Date.now(),rentalId:r.id,customer:r.customer,vehicle:r.vehicle,type:$('#inspectionType').value,mileage:Number($('#inspectionMileage').value),fuel:$('#inspectionFuel').value,notes:$('#inspectionNotes').value,date:new Date().toISOString(),photos});save();e.target.reset();closeInspectionModal()};
function renderInspections(){$('#inspectionCards').innerHTML=data.inspections.length?data.inspections.map(i=>`<article class="maintenance-card"><h3>${esc(i.vehicle)}</h3><p>${i.type} • ${Number(i.mileage).toLocaleString()} miles • Fuel: ${esc(i.fuel)}</p><p>${esc(i.notes||'No damage notes')}</p>${i.photos?.length?`<div class="photo-grid">${i.photos.map(p=>`<img src="${p}" alt="Inspection photo">`).join('')}</div>`:''}</article>`).join(''):'<p class="muted">No inspections recorded.</p>'}

function reminderInfo(r){const due=new Date(r.return+'T17:00:00'),now=new Date(),hrs=Math.round((due-now)/3600000);if(r.status==='Completed')return null;if(hrs<0)return{label:'OVERDUE',text:`Return was due ${Math.abs(hrs)} hour(s) ago.`,urgent:true};if(hrs<=Number(data.settings.reminderHours||24))return{label:'DUE SOON',text:`Return due in about ${hrs} hour(s).`,urgent:false};return{label:'SCHEDULED',text:`Reminder window begins ${Math.max(0,hrs-Number(data.settings.reminderHours||24))} hour(s) from now.`,urgent:false}}
function renderReminders(){const list=data.rentals.map(r=>[r,reminderInfo(r)]).filter(x=>x[1]);$('#reminderList').innerHTML=list.length?list.map(([r,i])=>`<article class="customer-card reminder-card"><strong>${esc(r.customer)} — ${esc(r.vehicle)}</strong><p>${esc(r.return)} • ${i.text}</p>${badge(i.label==='OVERDUE'?'Overdue':'Service')}</article>`).join(''):'<p class="muted">No reminders needed.</p>'}
$('#notificationBtn').onclick=async()=>{if(!('Notification'in window)){alert('This browser does not support notifications.');return}const p=await Notification.requestPermission();if(p==='granted'){new Notification('City Life Cars',{body:'Browser return alerts are enabled while this system is being used.'})}};

function renderSettings(){$('#defaultLateFee').value=data.settings.defaultLateFee??35;$('#paymentLink').value=data.settings.paymentLink||'';$('#reminderHours').value=data.settings.reminderHours??24}
$('#settingsForm').onsubmit=e=>{e.preventDefault();data.settings.defaultLateFee=Number($('#defaultLateFee').value);data.settings.paymentLink=$('#paymentLink').value.trim();data.settings.reminderHours=Number($('#reminderHours').value);save();alert('Settings saved.')};
$('#paymentLinkBtn').onclick=()=>{if(!data.settings.paymentLink){switchView('settings');alert('Add your Stripe or Square hosted payment link first.');return}window.open(data.settings.paymentLink,'_blank','noopener')};
$('#backupBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`city-life-cars-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#restoreInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const fr=new FileReader();fr.onload=()=>{try{const restored=JSON.parse(fr.result);if(!restored.vehicles||!restored.rentals)throw new Error();data=restored;save();alert('Backup restored.')}catch{alert('That file is not a valid City Life Cars backup.')}};fr.readAsText(file)};
$('#resetBtn').onclick=()=>{if(confirm('Reset all local demo records?')){data=structuredClone(seed);save()}};
$('#exportBtn').onclick=()=>{const rows=[['Year','Make','Model','Plate','Mileage','Daily Rate','Status','Revenue','GPS'],...data.vehicles.map(v=>[v.year,v.make,v.model,v.plate,v.mileage,v.rate,v.status,v.revenue,v.gps||''])];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='city-life-cars-fleet-report.csv';a.click()};
renderAll();
